# Generated by Django 4.2.4 on 2023-08-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pay_status',
            field=models.BooleanField(null=True),
        ),
    ]
